version: '3.8'
services:
    db:
        image: mariadb:10.8.3
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ./mysql/data/:/var/lib/mysql

    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8000:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=123456
